spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/securedb
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update   # <-- uncomment this
    show-sql: true       # (optional) to log the SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # ensure the correct dialect is set
server:
  port: 9090
